# Generated by Django 4.1 on 2022-08-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="maker",
            name="name",
            field=models.CharField(default=2, max_length=512),
            preserve_default=False,
        ),
    ]
